// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI agent that analyzes the sentiment of a news article.
 *
 * - summarizeArticleSentiment - A function that analyzes the sentiment of a news article.
 * - SummarizeArticleSentimentInput - The input type for the summarizeArticleSentiment function.
 * - SummarizeArticleSentimentOutput - The return type for the summarizeArticleSentiment function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const SummarizeArticleSentimentInputSchema = z.object({
  title: z.string().describe('The title of the news article.'),
  summary: z.string().describe('A brief summary of the news article.'),
});
export type SummarizeArticleSentimentInput = z.infer<typeof SummarizeArticleSentimentInputSchema>;

const SummarizeArticleSentimentOutputSchema = z.object({
  sentiment: z
    .enum(['positive', 'negative', 'neutral'])
    .describe('The sentiment of the news article.'),
  reasoning: z.string().describe('The reasoning behind the sentiment analysis.'),
});
export type SummarizeArticleSentimentOutput = z.infer<typeof SummarizeArticleSentimentOutputSchema>;

export async function summarizeArticleSentiment(
  input: SummarizeArticleSentimentInput
): Promise<SummarizeArticleSentimentOutput> {
  return summarizeArticleSentimentFlow(input);
}

const summarizeArticleSentimentPrompt = ai.definePrompt({
  name: 'summarizeArticleSentimentPrompt',
  input: {
    schema: z.object({
      title: z.string().describe('The title of the news article.'),
      summary: z.string().describe('A brief summary of the news article.'),
    }),
  },
  output: {
    schema: z.object({
      sentiment:
        z.enum(['positive', 'negative', 'neutral']).describe('The sentiment of the news article.'),
      reasoning: z.string().describe('The reasoning behind the sentiment analysis.'),
    }),
  },
  prompt: `Analyze the sentiment of the following news article based on its title and summary.\n\nTitle: {{{title}}}\nSummary: {{{summary}}}\n\nDetermine if the sentiment is positive, negative, or neutral. Explain your reasoning in a few sentences.`, // Changed the prompt to request reasoning.
});

const summarizeArticleSentimentFlow = ai.defineFlow<
  typeof SummarizeArticleSentimentInputSchema,
  typeof SummarizeArticleSentimentOutputSchema
>(
  {
    name: 'summarizeArticleSentimentFlow',
    inputSchema: SummarizeArticleSentimentInputSchema,
    outputSchema: SummarizeArticleSentimentOutputSchema,
  },
  async input => {
    const {output} = await summarizeArticleSentimentPrompt(input);
    return output!;
  }
);
